name: CD
on:
  push:
    branches:
    - prod

  jobs:
    deployed:
      runs-on: ubuntu_latest

      steps:
        - name: install checkout
          uses: actions/checkout@v7

        - name: install node
          uses: actions/setup-node@v4
          with:
            node-version: 26
            cache: "npm"

        - name: install dependencies
          run: npm install

        - name: build app
          run: npm build

        - name: Upload app to https
          uses: appleboy/scp-action@0.1.7
          with:
            host: ${{ secret.HOST }}
            username: ${{ secret.USER }}
            key: ${{ secret.PASS }}
            source: "out"
            target: "var/www/httpdocs/"
